<#
.SYNOPSIS
  Install grokrc as a Scheduled Task so it starts with your session.

.DESCRIPTION
  The Windows counterpart to packaging/systemd/install.sh, and deliberately the
  same SHAPE as that systemd *user* unit rather than a Windows Service:

    · runs as YOU, not as SYSTEM — it needs ~/.grok/auth.json, and the agents it
      spawns must have your file permissions
    · needs no administrator rights to install, start, or remove
    · starts automatically at logon and keeps running
    · restarts on failure, with a limit so a bad config does not crash-loop

  A Windows Service was considered and rejected: services run as SYSTEM or need
  a stored password, and a coding agent running as SYSTEM is the wrong answer to
  every question.

  WHERE THIS DIFFERS FROM SYSTEMD, honestly:

    · systemd starts at BOOT with lingering enabled. A Scheduled Task registered
      for your account starts at LOGON. Running before logon means "run whether
      the user is logged on or not", which requires storing your password and
      loses access to network resources. Not worth it for a tool you drive from
      your phone while your desktop is up. Use -RunWhetherLoggedOn if you
      disagree; it will prompt for credentials.
    · journald captures stdout. Task Scheduler does not, so output is redirected
      to a log file (see -LogPath). `journalctl --user -u grokrc -f` becomes
      `Get-Content <log> -Wait`.
    · systemd sends SIGTERM and waits. Task Scheduler's "stop" terminates. The
      daemon's own SIGINT/SIGTERM handlers still run when stopped with
      uninstall.ps1 or Stop-ScheduledTask, but a forced kill has no grace period.

.PARAMETER DaemonArgs
  Flags passed through to `grokrc up`, e.g. '--lan' or '--port 4319 --history 20'.
  Re-run this script to change them — the same as re-running install.sh.

.EXAMPLE
  packaging\windows\install.ps1
  packaging\windows\install.ps1 -DaemonArgs '--lan'
  packaging\windows\install.ps1 -DaemonArgs '--host 100.119.149.50'
#>
[CmdletBinding()]
param(
  [string]$DaemonArgs = '',
  [string]$TaskName = 'grokrc',
  [string]$LogPath = (Join-Path $env:LOCALAPPDATA 'grokrc\grokrc.log'),
  [switch]$RunWhetherLoggedOn
)

$ErrorActionPreference = 'Stop'

$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$Entry = Join-Path $RepoRoot 'dist\cli.js'

Write-Host 'grokrc Scheduled Task installer'
Write-Host "  repo:  $RepoRoot"

# The task runs `node dist/cli.js`, so the build must exist. Fail loudly rather
# than installing something that will crash-loop on first start.
if (-not (Test-Path $Entry)) {
  Write-Host '  building (dist/ missing)...'
  Push-Location $RepoRoot
  try { & npm run build | Out-Null } finally { Pop-Location }
}
if (-not (Test-Path $Entry)) { throw "build produced no $Entry" }

# Absolute node path. A Scheduled Task does not inherit an interactive PATH, so
# a bare `node` resolves differently under nvm-windows/Volta, or not at all.
$NodeBin = (Get-Command node -ErrorAction SilentlyContinue).Source
if (-not $NodeBin) { throw 'node not found on PATH' }
Write-Host "  node:  $NodeBin"

if (-not (Get-Command grok -ErrorAction SilentlyContinue)) {
  Write-Host '  ! grok not found on PATH - the daemon will refuse to start.'
  Write-Host '    Install it from Git Bash: curl -fsSL https://x.ai/cli/install.sh | bash'
  Write-Host '    then add %USERPROFILE%\.grok\bin to your PATH.'
}

$StateDir = Split-Path $LogPath
New-Item -ItemType Directory -Force -Path $StateDir | Out-Null
$Launcher = Join-Path $StateDir 'run-grokrc.ps1'

# A generated launcher SCRIPT, not an inline -Command.
#
# Two reasons, the first found the hard way:
#
#  1. Quoting. The command line has to carry three quoted paths (node, the
#     entry, the log) inside one already-quoted -Command argument. Task
#     Scheduler hands that string to powershell.exe verbatim, the inner quotes
#     terminate it early, and the task exits 1 having produced NO log — the one
#     artifact that would have explained it. `-File` needs one level of quoting
#     and cannot fail this way.
#
#  2. It restores the property that made systemd's EnvironmentFile good: a
#     generated file you can open, read, and edit, rather than configuration
#     buried in an argument string. Re-run this installer to regenerate it.
#
# stdout and stderr are redirected because Task Scheduler captures neither, and
# a daemon whose logs you cannot read is a daemon you cannot debug.
$launcherBody = @"
# Generated by packaging/windows/install.ps1 - safe to edit.
# Apply changes with:  Stop-ScheduledTask -TaskName $TaskName; Start-ScheduledTask -TaskName $TaskName
#
# A Scheduled Task does not inherit an interactive PATH. The daemon refuses to
# start without ``grok``, so its directory is prepended explicitly rather than
# assumed.
`$env:Path = "`$env:USERPROFILE\.grok\bin;`$env:Path"
Set-Location "$RepoRoot"

# node writes UTF-8. Without this, PowerShell decodes its output with the OEM
# code page and the log renders the daemon's own warning as
# "ΓÜá reachable from other machines" - which is the line most worth reading.
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
`$OutputEncoding = [System.Text.Encoding]::UTF8

# Clear our own orphan before binding.
#
# systemd puts a service in a cgroup and kills the whole tree. Task Scheduler
# terminates only the process it launched - this powershell - and the node child
# survives, still holding the port. MEASURED: Stop-ScheduledTask followed by
# Start-ScheduledTask died with EADDRINUSE on 4319 while /api/health kept
# answering from the orphan, so the service looked healthy while the task was
# crash-looping.
#
# Scoped by the FULL entry path, so this can only ever match a daemon started
# from this checkout - never another node process, and never another install.
Get-CimInstance Win32_Process -Filter "Name='node.exe'" -ErrorAction SilentlyContinue |
  Where-Object { `$_.CommandLine -and `$_.CommandLine.Contains("$Entry") } |
  ForEach-Object {
    "clearing orphaned daemon pid `$(`$_.ProcessId)" *>> "$LogPath"
    Stop-Process -Id `$_.ProcessId -Force -ErrorAction SilentlyContinue
  }
Start-Sleep -Milliseconds 500

& "$NodeBin" "$Entry" up $DaemonArgs *>> "$LogPath"
"@
Set-Content -Path $Launcher -Value $launcherBody -Encoding utf8
Write-Host "  launcher: $Launcher"

$action = New-ScheduledTaskAction -Execute 'powershell.exe' `
  -Argument "-NoProfile -NonInteractive -WindowStyle Hidden -ExecutionPolicy Bypass -File `"$Launcher`"" `
  -WorkingDirectory $RepoRoot

$trigger = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME

# ExecutionTimeLimit 0 = never kill it for running too long; this is a daemon.
# RestartCount/Interval are the analogue of Restart=on-failure + RestartSec,
# and StartWhenAvailable covers a missed trigger (asleep at logon time).
$settings = New-ScheduledTaskSettingsSet `
  -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
  -StartWhenAvailable `
  -ExecutionTimeLimit ([TimeSpan]::Zero) `
  -RestartCount 5 -RestartInterval (New-TimeSpan -Minutes 1) `
  -MultipleInstances IgnoreNew

if ($RunWhetherLoggedOn) {
  # Requires a stored password, and loses access to network resources under S4U.
  $principal = New-ScheduledTaskPrincipal -UserId "$env:USERDOMAIN\$env:USERNAME" -LogonType Password
  Write-Host '  ! -RunWhetherLoggedOn: you will be prompted for your password.'
} else {
  $principal = New-ScheduledTaskPrincipal -UserId "$env:USERDOMAIN\$env:USERNAME" -LogonType Interactive
}

# Re-registering is the documented way to change flags, so an existing task is
# replaced rather than left with the old arguments — the same reason install.sh
# restarts unconditionally instead of using `enable --now`.
if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) {
  Write-Host "  replacing existing task '$TaskName'"
  Stop-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
  Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
}

Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger `
  -Settings $settings -Principal $principal `
  -Description 'grokrc - remote control for Grok Build' `
  -ErrorAction Stop | Out-Null

# TWIN of the same defect found in install-watchdog.ps1: Register-ScheduledTask
# reports a rejected task XML or a denied permission as a NON-TERMINATING CIM
# error, which $ErrorActionPreference='Stop' does not catch. That script printed
# "installed watchdog task" while nothing had been registered. Verify before
# claiming, in both.
if (-not (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue)) {
  throw "registration reported no error but '$TaskName' does not exist - nothing was installed"
}

Write-Host "  task:  $TaskName"
Write-Host "  log:   $LogPath"
Write-Host "  args:  $(if ($DaemonArgs) { $DaemonArgs } else { '(none)' })"

Start-ScheduledTask -TaskName $TaskName
Start-Sleep -Seconds 3

$info = Get-ScheduledTask -TaskName $TaskName | Get-ScheduledTaskInfo
Write-Host ''
Write-Host "  state:     $((Get-ScheduledTask -TaskName $TaskName).State)"
Write-Host "  last run:  $($info.LastRunTime)  result=$($info.LastTaskResult)"
Write-Host ''
Write-Host "  logs:    Get-Content '$LogPath' -Wait -Tail 40"
Write-Host "  restart: Stop-ScheduledTask -TaskName $TaskName; Start-ScheduledTask -TaskName $TaskName"
Write-Host "  stop:    Stop-ScheduledTask -TaskName $TaskName"
Write-Host "  remove:  packaging\windows\uninstall.ps1"
