#!/usr/bin/env bash
#
# Install grokrc as a systemd *user* service so it survives logout and reboot.
#
# No sudo. Everything lives under ~/.config, and the daemon runs as you — which
# it must, since it needs ~/.grok/auth.json and spawns agents with your
# permissions.
#
#   packaging/systemd/install.sh [-- <grokrc up args>]
#
# Examples:
#   packaging/systemd/install.sh
#   packaging/systemd/install.sh -- --port 4319 --history 20
#   packaging/systemd/install.sh -- --lan            # reachable on your LAN
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ENTRY="$REPO_ROOT/dist/cli.js"
UNIT_SRC="$REPO_ROOT/packaging/systemd/grokrc.service"
UNIT_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
ENV_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/grokrc"
ENV_FILE="$ENV_DIR/grokrc.env"

# Args after `--` are passed through to `grokrc up`.
ARGS=""
if [[ "${1:-}" == "--" ]]; then
  shift
  ARGS="$*"
fi

echo "grokrc systemd installer"
echo "  repo:  $REPO_ROOT"

# The unit runs `node dist/cli.js`, so the build must exist. Fail loudly rather
# than installing a service that will crash-loop on first start.
if [[ ! -f "$ENTRY" ]]; then
  echo "  building (dist/ missing)…"
  (cd "$REPO_ROOT" && npm run build >/dev/null)
fi
[[ -f "$ENTRY" ]] || { echo "  ✗ build produced no $ENTRY"; exit 1; }

NODE_BIN="$(command -v node || true)"
[[ -n "$NODE_BIN" ]] || { echo "  ✗ node not found on PATH"; exit 1; }

if ! command -v grok >/dev/null; then
  echo "  ⚠ grok not found on PATH — install it, or the daemon will start but"
  echo "    be unable to spawn agents: curl -fsSL https://x.ai/cli/install.sh | bash"
fi

mkdir -p "$UNIT_DIR" "$ENV_DIR"

# Absolute node path: systemd user units do not inherit an interactive PATH, so
# a bare `node` resolves differently (or not at all) under nvm/asdf.
cat >"$ENV_FILE" <<EOF
# Generated by packaging/systemd/install.sh — safe to edit.
# Apply changes with: systemctl --user restart grokrc
GROKRC_NODE=$NODE_BIN
GROKRC_ENTRY=$ENTRY
GROKRC_ARGS=$ARGS
EOF
echo "  env:   $ENV_FILE"

install -m 0644 "$UNIT_SRC" "$UNIT_DIR/grokrc.service"
echo "  unit:  $UNIT_DIR/grokrc.service"

systemctl --user daemon-reload
systemctl --user enable grokrc.service
# `enable --now` does NOT restart a service that is already running, so
# re-running the installer with different args would silently keep the old ones.
# Restart unconditionally: this script's whole job is to apply the current config.
systemctl --user restart grokrc.service

# Without lingering, user units stop at logout and never start at boot — which
# defeats the point of installing a service at all.
if command -v loginctl >/dev/null; then
  if [[ "$(loginctl show-user "$USER" -p Linger --value 2>/dev/null || echo no)" != "yes" ]]; then
    echo "  enabling linger (survive logout/reboot)…"
    loginctl enable-linger "$USER" 2>/dev/null \
      || echo "  ⚠ could not enable linger; run: sudo loginctl enable-linger $USER"
  fi
fi

sleep 1
echo
systemctl --user --no-pager status grokrc.service | head -12 || true
echo
echo "  logs:    journalctl --user -u grokrc -f"
echo "  restart: systemctl --user restart grokrc"
echo "  stop:    systemctl --user stop grokrc"
echo "  remove:  packaging/systemd/uninstall.sh"
